use_frameworks!
project 'demo_ua.xcodeproj'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demo_ua' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  

  # Pods for demo_ua
  pod 'UrbanAirship-iOS-SDK', '~>8.3'
  target 'demo_ua-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'demo_uaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'demo_ua-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

end
